config/routes.rb
Rails.application.routes.draw do
  resources :empresa_factures
  resources :usuari_factures
  resources :empresa_facturas
  resources :usuari_facturas
  get 'documents/index'
  get 'edificis/pdf_header'

  resources :tresoreries
  resources :ingressos
  resources :despeses
  get 'planificacions/fases', to: 'planificacions#fases', :as => :fases_planificacio
  get 'planificacions/calendari', to: 'planificacions#calendari', :as => :calendari
  get 'planificacions/crea_valors_inicials', to: 'planificacions#crea_valors_inicials', :as => :crea_valors_inicials
  resources :planificacions
  resources :fases
  #get 'intervencions/assignacions', to: 'intervencions#assignacions', :as => :assignacions
  get 'intervencions/exporta_xml', to: 'intervencions#exporta_xml', :as => :exporta_xml
  resources :intervencions do
    collection do
      get :assignacions
      put :assigna
    end
  end

  resources :deficiencies
  resources :qualificacions

  get 'pagaments/crear_pagament', to: 'pagaments#crear_pagament', :as => :crear_pagament
  get 'pagaments/validar_dades', to: 'pagaments#validar_dades', :as => :validar_dades 

  resources :edificis do
    resource :download, only: [:show]
  end
  resources :identificacions
  
  devise_for :users
  get 'home/index'
  get 'home/contacta'
  get 'home/permisos'
  get 'home/tutorial'

  
  root :to => "home#index"
end

app/models/pagament.rb
class Pagament < ActiveRecord::Base

	belongs_to :edifici
	belongs_to :user

end

app/controllers/pagaments_controller.rb
class PagamentsController < ApplicationController
  # Posem skip pq vindrà d'un servidor extern i no hi haurà authenticity token
  skip_before_filter :verify_authenticity_token
  before_action :set_pagament, only: [:show, :edit, :update, :destroy]
  before_action :set_edifici, only: [:index, :show, :new, :edit, :create, :destroy]

  # GET /pagaments
  # GET /pagaments.json
  def index
    @pagaments = Pagament.where(pagat: true)
  end

  # GET /pagaments/1
  # GET /pagaments/1.json
  def show
  end

  # GET /pagaments/new
  def new
    @pagament = Pagament.new
  end

  # GET /pagaments/1/edit
  def edit
  end

  def validar_dades
    @edifici = Edifici.find(params[:edifici_id])
    @usuari_factura = UsuariFactura.new
    @empresa_factura = EmpresaFactura.new
    @nif_usuari = current_user.nif

  end

  #def crear_pagament_old
  #  @pagament = Pagament.new()
  #  @pagament.user_id = current_user.id
  #  @pagament.edifici_id = params[:edifici_id]
  #  @pagament.numorder = numorder(params[:edifici_id])
  #  @pagament.import = "42,96"
  #  @pagament.pagat = false
  #  titular = current_user.name
  #  url_pagament = 'http://isis.apabcn.cat/LibroEdificio/pagoVisa.aspx?titular=' + titular + '&importe=' + @pagament.import + '&numorder=' + @pagament.numorder.to_s + '&descripcion=llibreedifici&urlresponse=http://llibreedifici.apabcn.cat/pagaments/update_pagament'
  #  #http://isis.apabcn.cat/LibroEdificio/pagoVisa.aspx?titular=Titular&importe=42,96&numorden=110000000101&descripcion=llibreedifici&urlresponse=http://llibreedifici.apabcn.cat/pagaments/update_pagament
  #  respond_to do |format|
  #    if @pagament.save
  #      format.html { redirect_to url_pagament }
  #      format.json { render :show, status: :created, location: @pagament }
  #    else
  #      format.html { render :new }
  #      format.json { render json: @pagament.errors, status: :unprocessable_entity }
  #    end
  #  end
  #end

  def crear_pagament
    @pagament = Pagament.new()
    @pagament.user_id = current_user.id
    @pagament.edifici_id = params[:edifici_id]
    @pagament.numorder = numorder(params[:edifici_id])
    @pagament.import = preu(params[:edifici_id])
    tipus_factura = comprova_factura(params[:edifici_id])
    if tipus_factura == 'usuari'
      factura = UsuariFactura.where(edifici_id: params[:edifici_id]).last
    else
      factura = EmpresaFactura.where(edifici_id: params[:edifici_id]).last
    end
    @pagament.num_visat_ite = factura.num_visat_ite
    @pagament.pagat = false
    titular = current_user.name
    #endpoint = 'https://partial-caateebcn-partial.cs82.force.com/bookpurchase/apex/creditcardservice?importe=' + @pagament.import + '&titular=' + URI.escape(titular) + '&descripcion=llibreedifici&idProducto=' + params[:edifici_id] + '&urlresponse=http%3A%2F%2Flocalhost:3000%2Fpagaments%2Fupdate_pagament%3FpagoVisaResult%3Dvalue1%26numorder%3Dvalue2&urlresponseko=http%3A%2F%2Flocalhost:3000%2Fpagaments%2Ferror_factura'
    #url = URI.parse('https://partial-caateebcn-partial.cs82.force.com/bookpurchase/services/apexrest/creditcard')
    #url = URI.parse('https://enngarvpspmm.x.pipedream.net')
    url_resposta_correcta = "http%3A%2F%2Fprogramarehabilitacio.apabcn.cat%2Fpagaments%2Fupdate_pagament%3FpagoVisaResult%3Dvalue1%26numorder%3D" + @pagament.numorder
    url_resposta_error = "http%3A%2F%2Fprogramarehabilitacio.apabcn.cat%2Fpagaments%2Ferror_pagament"
    args = {"importe" => @pagament.import, "titular" => URI.escape(titular), "descripcion" => "progrehab", "idProducto" => params[:edifici_id], "urlresponse" => url_resposta_correcta, "urlresponseint" => url_resposta_error}
    
    urlstring = 'https://apabcn.secure.force.com/bookpurchase/services/apexrest/creditcard'
    #urlstring = URI.parse('https://enngarvpspmm.x.pipedream.net')
    #uri = URI.parse("https://partial-caateebcn-partial.cs82.force.com/bookpurchase/services/apexrest/creditcard")

    if @pagament.save
      #resposta = Net::HTTP.post_form(url, args, initheader = {'Content-Type' =>'application/json'})

      #uri = URI.parse("https://enngarvpspmm.x.pipedream.net")
      #header = {'Content-Type': 'text/json'}
      #http = Net::HTTP.new(uri.host, uri.port)
      #request = Net::HTTP::Post.new(uri.request_uri, header)
      #request.body = args.to_json
      #resposta = http.request(request)

      
      
      resposta = HTTParty.post(urlstring, body: args.to_json, headers: { 'Content-Type' => 'application/json' })
      #resposta = Net::HTTP.post_form(uri, {"importe" => @pagament.import, "titular" => URI.escape(titular), "descripcion" => "llibreedifici", "idProducto" => params[:edifici_id], "urlresponse" => "http%3A%2F%2Flocalhost:3000%2Fpagaments%2Fupdate_pagament%3FpagoVisaResult%3Dvalue1%26numorder%3Dvalue2", "urlresponseko" => "http%3A%2F%2Flocalhost:3000%2Fpagaments%2Ferror_factura"})
      puts '-----------------'
      puts resposta.code
      puts '-----------------'
      puts resposta.body
      puts '-----------------'
      puts resposta.message
      puts '-----------------'
      #puts resposta.headers.inspect
      puts '-----------------'
      dades = resposta.to_hash
      @pagament.numorden = dades['numorden']
      @pagament.save
      htmlstring = dades['pagoVisaResult']
      htmlstring.slice!(0, 9)
      htmlstring = 3.times do htmlstring.chop! end
      render html: dades['pagoVisaResult'].html_safe

    end
  end

  def preu(edifici_id)
    #Comprovem si hi ha factura d'usuari i empresa i seleccionem quin tipus de factura fem
    factura_usuari = UsuariFactura.where(edifici_id: edifici_id).last
    factura_empresa = EmpresaFactura.where(edifici_id: edifici_id).last
    tipus_factura = comprova_factura(edifici_id)
    if tipus_factura == "usuari"
      if factura_usuari.colegiat == true
        if factura_usuari.num_visat_ite != nil && factura_usuari.num_visat_ite != ''
          #Aquí hauríem de cobrar 9.08 però de moment cobrem igual fins que quedi controlat el tema de visats
          return "18.15"
        else
          return "18.15"
        end
      else
        return "24.2"
      end
      puts "Numero de visat:"
      puts factura_usuari.num_visat_ite
    else
      #Comprovem si té número de client, que podria ser nil
      if factura_empresa.numclient != nil
        if factura_empresa.numclient > "19999" && factura_empresa.numclient < "30000"
          if factura_empresa.num_visat_ite != nil && factura_empresa.num_visat_ite != ''
            return "18.15"
          else
            return "18.15"
          end
        else
          return "24.2"
        end
      else
        return "24.2"
      end
    end
  end

  def comprova_factura(edifici_id)
    #Comprovem si hi ha factura d'usuari i empresa i seleccionem quin tipus de factura fem
    factura_usuari = UsuariFactura.where(edifici_id: edifici_id).last
    factura_empresa = EmpresaFactura.where(edifici_id: edifici_id).last
    if factura_usuari == nil
      if factura_empresa == nil
        return "no_factura"
      else
        tipus_factura = "empresa"
      end
    elsif factura_usuari != nil && factura_empresa != nil
      #Comprovem si l'última factura és per usuari o empresa en el cas que n'hi hagi dues
      if factura_usuari.created_at < factura_empresa.created_at
        tipus_factura = "empresa"
      else
        tipus_factura = "usuari"
      end
    else
      tipus_factura = "usuari"
    end
    return tipus_factura
  end


  def numorder(edifici_id)
    codi_factura = '058'
    projecte = edifici_id
    numero_projecte = sprintf '%07d', projecte
    intent = Pagament.where(edifici_id: edifici_id).count + 1
    numero_intent = sprintf '%02d', intent
    final = codi_factura + numero_projecte + numero_intent
    return final
  end

  # PATCH/PUT /pagaments/1
  # PATCH/PUT /pagaments/1.json
  #def update
  #  pagament = Pagament.where(:numorder => params[:numorder])
  #  respond_to do |format|
  #    if pagament.update(pagament_params)
  #      format.html { redirect_to @pagament, notice: 'Pagament was successfully updated.' }
  #      format.json { render :show, status: :ok, location: @pagament }
  #    else
  #      format.html { render :edit }
  #      format.json { render json: @pagament.errors, status: :unprocessable_entity }
  #    end
  #  end
  #end

  #Comprovem si el resultat del pagament és entre 0000 i 0099
  def comprovar_resultat(resultat)
    #Primer comprovem els dos dígits inicials, han de ser 00 per a que sigui correcte
    numero_caracters = resultat.length
    primer_valor = resultat.split(//).first(2).join
    segon_valor = resultat.split(//).last(2).join
    if numero_caracters == 4 && primer_valor == '00' && segon_valor.to_i < 100
      return true
    else
      return false
    end
  end

  def update_pagament                  
    pagament = Pagament.where(:numorder => params[:numorder]).last
    if pagament != nil
      if pagament.numorder != nil
        pagament.pagat = true
        if pagament.factura_enviada != true
          # Especifiquem que s'ha enviat una factura per evitar duplicats de factures si s'executa de nou update_pagament
          pagament.factura_enviada = true
          pagament.save
          # Enviem la factura
          @resultat_enviament = envia_factura(pagament) 
          @info_pagament = pagament
        end
      end
    end
  end

  def envia_factura(pagament)
    # Comprovem si l'última factura d'aquest edifici és d'usuari o d'empresa
    factura_usuari = UsuariFactura.where(edifici_id: pagament.edifici_id).last
    factura_empresa = EmpresaFactura.where(edifici_id: pagament.edifici_id).last
    #client = Savon.client(wsdl: "http://isis.apabcn.cat/LibroEdificio/wsfacturasSap.asmx?wsdl")
    #client = Savon.client(wsdl: "https://partial-caateebcn-partial.cs82.force.com/bookpurchase/services/Soap/class/BookPurchaseService")
    urlstring = 'https://apabcn.secure.force.com/bookpurchase/services/apexrest/books'

    if factura_usuari != nil && factura_empresa != nil

app/helpers/pagaments_helper.rb
module PagamentsHelper
end

app/views/pagaments/_form.html.erb
<%= simple_form_for([@edifici, @pagament]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :edifici_id, :as => :hidden, :input_html => { :value => @edifici.id } %>

  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/pagaments/cambra_projects.html.erb
<div class="background-seccio">
	<div class="row">
		<div class="large-12 columns">
			<div class="titol-seccio">
				Llibres Cambra
			</div>

			<div class="llistat-llibres-cambra">
				<% for i in 0..11 %>
					<h3 class="llistat-llibres-cambra-mes"><%= @mesos[i][0] %></h3>
					<h4 class="llistat-llibres-cambra-nombre">Llibres: <%= @edificis[i].count %></h4>
					<% if @edificis[i].count > 0 %>
						<table class="llistat-llibres-cambra-taula">
						  <thead>
						    <tr>
						      <th>ID</th>
						      <th>Nom</th>
						      <th>NIF editor</th>
						      <th>Data</th>
						    </tr>
						  </thead>

						  <tbody>
						    <% @edificis[i].each do |edifici| %>
						      <tr>
						      	<td><%= edifici.id %></td>
						        <td><%= edifici.nom_edifici %></td>
						        <td><%= edifici.editor_nif %></td>
						        <td><%= edifici.created_at %></td>
						      </tr>
						    <% end %>
						  </tbody>
						</table>
					<% end %>
					<hr/>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/pagaments/crear_pagament.html.erb
<%= @resposta %>
		

app/views/pagaments/detall_pagament.html.erb
<div class="background-seccio">
	<div class="row">
		<div class="large-12 columns">
			<div class="titol-seccio">
				<h3>Dades del pagament</h3>
			</div>

			<div class="detall-pagament">
				<strong>Nom:</strong> <%= @pagament.user.name %> <br/>
				<strong>NIF:</strong> <%= @pagament.user.nif %> <br/>
				<strong>Edifici:</strong> <%= @pagament.edifici_id %> <br/>
				<strong>Numorder:</strong> <%= @pagament.numorder %> <br/>
				<strong>Pagat:</strong> <%= @pagament.pagat %> <br/>
				<strong>Data:</strong> <%= @pagament.created_at %> <br/>

				<br/>
				<hr/>

				<h4>Dades de la factura</h4>
				<% if @usuari_factura.present? %>
					<h5>Factura a nom propi</h5>
					<strong>Nom:</strong> <%= @usuari_factura.nom %> <br/>
    			<strong>NIF:</strong> <%= @usuari_factura.nif %> <br/>
    			<strong>Població:</strong> <%= @usuari_factura.poblacio %> <br/>
			    <strong>Provincia:</strong> <%= @usuari_factura.provincia %> <br/>
			    <strong>Codi postal:</strong> <%= @usuari_factura.codi_postal %> <br/>
			    <strong>Adreça:</strong> <%= @usuari_factura.adreca %> <br/>
			    <strong>Correu:</strong> <%= @usuari_factura.email %> <br/>
			    <strong>Número client:</strong> <%= @usuari_factura.num_client %> <br/>
			    <strong>Col·legiat:</strong> <%= @usuari_factura.colegiat %> <br/>
				<% end %>

				<% if @empresa_factura.present? %>
					<h5>Factura a nom d'empresa</h5>
					<% if @pagament.factura_enviada == false %>
						Atenció: la factura no es va enviar
					<% end %>
					<strong>Nom jurídic:</strong> <%= @empresa_factura.nom_juridic %> <br/>
    			<strong>CIF:</strong> <%= @empresa_factura.nif %> <br/>
    			<strong>Població:</strong> <%= @empresa_factura.poblacio %> <br/>
    			<strong>Provincia:</strong> <%= @empresa_factura.provincia %> <br/>
    			<strong>Codi postal:</strong> <%= @empresa_factura.codi_postal %> <br/>
    			<strong>Adreça:</strong> <%= @empresa_factura.adreca %> <br/>
    			<strong>Pais:</strong> <%= @empresa_factura.pais %> <br/>
    			<strong>Correu:</strong> <%= @empresa_factura.email %> <br/>
    			<strong>Tipus client:</strong> <%= @empresa_factura.tipus_client %> <br/>
				<% end %>

			</div>

			<br/>
			<hr/>

			<%= link_to "Tornar al llistat dels últims pagaments", pagaments_llistat_pagaments_path %>
		</div>
	</div>
</div>

app/views/pagaments/edit.html.erb
<h1>Editing Pagament</h1>

<%= render 'form' %>

<%= link_to 'Show', @pagament %> |
<%= link_to 'Back', pagaments_path %>

app/views/pagaments/error_factura.html.erb
<div class="projectes-background">
	<div class="row">
		<div class="medium-12 columns">
	    <div class="projectes-external-container">
	      <div class="projectes-title-container">
	        <span class="projectes-title">Error en la generació de la factura</span>
	      </div>
	      <div class="projectes-form-container">
					<p>S'ha produït un error en la generació de la factura. Poseu-vos en contacte amb l'àrea tècnica del CAATEEB.</p>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/pagaments/error_pagament.html.erb
<div class="projectes-background">
	<div class="row">
		<div class="medium-12 columns">
	    <div class="projectes-external-container">
	      <div class="projectes-title-container">
	        <span class="projectes-title">Error en el pagament</span>
	      </div>
	      <div class="projectes-form-container">
					<p>S'ha produït un error en el procés de pagament. Torneu a intentar fer el pagament o poseu-vos en contacte amb l'àrea tècnica del CAATEEB.</p>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/pagaments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Pagaments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Edifici</th>
      <th>Numorder</th>
      <th>Import</th>
      <th>Pagat</th>
      <th>Data</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pagaments.each do |pagament| %>
      <tr>
        <td><%= pagament.user_id %></td>
        <td><%= pagament.edifici_id %></td>
        <td><%= pagament.numorder %></td>
        <td><%= pagament.import %></td>
        <td><%= pagament.pagat %></td>
        <td><%= pagament.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/pagaments/llistat_pagaments.html.erb
<div class="background-seccio">
	<div class="row">
		<div class="large-12 columns">
			<div class="titol-seccio">
				Llistat dels últims pagaments
			</div>

			<div class="llistat-pagaments">
				<table>
				  <thead>
				    <tr>
				      <th>ID</th>
				      <th>Nom</th>
				      <th>NIF</th>
				      <th>Edifici</th>
				      <th>Numorder</th>
				      <th>Pagat</th>
				      <th>Data</th>
				    </tr>
				  </thead>

				  <tbody>
				    <% @pagaments.each do |pagament| %>
				      <tr>
				      	<td><%= link_to pagament.id, pagaments_detall_pagament_path(id: pagament.id) %></td>
				        <td><%= pagament.user.name %></td>
				        <td><%= pagament.user.nif %></td>
				        <td><%= pagament.edifici_id %></td>
				        <td><%= pagament.numorder %></td>
				        <td><%= pagament.pagat %></td>
				        <td><%= pagament.created_at %></td>
				      </tr>
				    <% end %>
				  </tbody>
				</table>
			</div>
		</div>
	</div>
</div>

app/views/pagaments/new.html.erb
<h1>New Pagament</h1>


<%= link_to 'pagar', crear_pagament_path %>

app/views/pagaments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @pagament.user_id %>
</p>

<p>
  <strong>Edifici:</strong>
  <%= @pagament.edifici_id %>
</p>

<p>
  <strong>Numorder:</strong>
  <%= @pagament.numorder %>
</p>

<p>
  <strong>Import:</strong>
  <%= @pagament.import %>
</p>

<p>
  <strong>Codi retorn:</strong>
  <%= @pagament.codi_retorn %>
</p>

<p>
  <strong>Codi autoritzacio:</strong>
  <%= @pagament.codi_autoritzacio %>
</p>

<%= link_to 'Edit', edit_pagament_path(@pagament) %> |
<%= link_to 'Back', pagaments_path %>

app/views/pagaments/update_pagament.html.erb
<div class="projectes-background">
	<div class="row">
		<div class="medium-12 columns">
	    <div class="projectes-external-container">
	      <div class="projectes-title-container">
	        <span class="projectes-title">Llibre de l'edifici</span>
	      </div>
	      <div class="projectes-form-container">
					<% if @info_pagament != nil %>
	
						<% if @info_pagament.pagat == true %>
							<p>El pagament s'ha efectuat correctament. Accediu als vostres <%= link_to "Llibres", edificis_path %> per editar el llibre de l'edifici.</p>
							
						<% else %>
							<p>Hi ha hagut un problema amb el pagament. Torneu a intentar-ho o poseu-vos en contacte amb l'àrea tècnica del CAATEEB.</p>
						<% end %>
						
						<% if @resultat_enviament == false %>
							<p>S'ha produït un error al generar la factura. Poseu-vos en contacte amb l'àrea tècnica del CAATEEB.</p>
						<% end %>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/pagaments/validar_dades.html.erb
<div class="dark-background-container">
	<div class="row">
		<div class="medium-6 medium-offset-3 columns">

			<% flash.each do |key, value| %>
		    <div class="row">
		      <div class="medium-12 columns end">
		        <% if key == 'notice'
		            key = 'success'
		            end %>
		        <% value["nif"].each do |erro| %>
			        <div data-alert class="alert-box alert <%= key %> radius">
			          <%= erro %>
			          <a href="#" class="close">&times;</a>
		        	</div>
		       	<% end %>
		      </div>
		    </div>
		  <% end %>


	    
      <div class="heavy-title-container">
        <h2 class="heavy-title"><%= t('.titol') %></h2>
      </div>
      <div class="projectes-form-container">
      	<p><%= t('.explicacio') %></p>
      	<div class="preu-llibre">
      		<div class="row">
      			<div class="medium-6 columns">
      				<%= image_tag('document_programa.png', :alt => t('.imatge_llibre'), :class => 'imatge-document document-right') %>
      			</div>
      			<div class="medium-6 columns">
		      		<div class="requadre-preu">
		      			18,15 €
		      		</div>
		      	</div>
		      </div>
		      <div class="row">
		      	<div class="medium-12 columns">
		      		<br>
		      		<p><%= t('.preu_no_colegiats') %></p>
		      		<p><%= t('.preu_ite') %></p>
		      		<label class="string"><%= t('.label_preu_ite') %></label>
		      		<input id="ite" type="text">
		      	</div>
		      </div>
      	</div>

      	<hr>

      	<p><%= t('.explicacio2') %></p>
      	<p><%= t('.explicacio3') %></p>
      	
      	<div class="row">
      		<div class="medium-6 columns">
		      	<div class="comprovacio-nif">
		      		<%= simple_form_for(@usuari_factura) do |f| %>
								<%= f.error_notification %>
								<div class="form-inputs">
				          <%= f.input :user_id, :as => :hidden, :input_html => { :value => current_user.id } %>
				          <%= f.input :edifici_id, :as => :hidden, :input_html => { :value => @edifici.id } %>
				          <%= f.input :num_visat_ite, :as => :hidden, :input_html => { :class => 'numero-ite' } %>
				          <%= f.input :nif, :input_html => { :value => @nif_usuari } %>
			          </div>

      					<div class="form-actions">
		              <%= f.button :submit, t('.factura_personal'), :class => 'button small radius' %>
		            </div>
		          <% end %>
      			</div>
    			</div>

		      <div class="medium-6 columns">
		      	<div class="comprovacio-nif">
		      		<%= simple_form_for(@empresa_factura) do |f| %>
								<%= f.error_notification %>
								<div class="form-inputs">
				          <%= f.input :user_id, :as => :hidden, :input_html => { :value => current_user.id } %>
				          <%= f.input :edifici_id, :as => :hidden, :input_html => { :value => @edifici.id } %>
				          <%= f.input :num_visat_ite, :as => :hidden, :input_html => { :class => 'numero-ite' } %>
				          <%= f.input :nif %>
			          </div>

      					<div class="form-actions">
		              <%= f.button :submit, t('.factura_empresa'), :class => 'button small radius' %>
		            </div>
		          <% end %>
      			</div>
		      </div>
		    </div>
      	
      </div>
      <br>
			<%= link_to t('.tornar_projectes'), edificis_path %>
		</div>
	</div>
</div>

<script>
	$('#ite').focusout(function() {
		$('.numero-ite').val($('#ite').val());
	});
</script>