config/routes.rb
Rails.application.routes.draw do
  resources :empresa_factures
  resources :usuari_factures
  resources :empresa_facturas
  resources :usuari_facturas
  get 'documents/index'
  get 'edificis/pdf_header'

  resources :tresoreries
  resources :ingressos
  resources :despeses
  get 'planificacions/fases', to: 'planificacions#fases', :as => :fases_planificacio
  get 'planificacions/calendari', to: 'planificacions#calendari', :as => :calendari
  get 'planificacions/crea_valors_inicials', to: 'planificacions#crea_valors_inicials', :as => :crea_valors_inicials
  resources :planificacions
  resources :fases
  #get 'intervencions/assignacions', to: 'intervencions#assignacions', :as => :assignacions
  get 'intervencions/exporta_xml', to: 'intervencions#exporta_xml', :as => :exporta_xml
  resources :intervencions do
    collection do
      get :assignacions
      put :assigna
    end
  end

  resources :deficiencies
  resources :qualificacions

  get 'pagaments/crear_pagament', to: 'pagaments#crear_pagament', :as => :crear_pagament
  get 'pagaments/validar_dades', to: 'pagaments#validar_dades', :as => :validar_dades 

  resources :edificis do
    resource :download, only: [:show]
  end
  resources :identificacions
  
  devise_for :users
  get 'home/index'
  get 'home/contacta'
  get 'home/permisos'
  get 'home/tutorial'

  
  root :to => "home#index"
end

app/controllers/usuari_factures_controller.rb
class UsuariFacturesController < ApplicationController
  before_action :set_usuari_factura, only: [:show, :edit, :update, :destroy]

  def index
    @usuari_factures = UsuariFactura.all
  end

  def show
  end

  def new
    @usuari_factura = UsuariFactura.new
  end

  def edit
    @edifici = Edifici.find(@usuari_factura.edifici_id)
  end

  def create
    @usuari_factura = UsuariFactura.new(usuari_factura_params)
    #De moment anul·lo la validació al crear les dades de factura. Això és perquè primer es va a la pàgina de validació de dades, on l'usuari només ha de posar el NIF. Si tinc una validació d'altres camps com email no puc passar a la següent pàgina. Quan es faci l'update, en la confirmació de dades, sí que hi haurà validació de tots els camps, inclòs el NIF.
    if @usuari_factura.save(validate: false)

    else
      redirect_to validar_dades_path(@edifici.id), flash: { error: @usuari_factura.errors.messages }
      return
    end
    # Guardem el NIF introduït per si no és el de l'usuari
    nou_nif = @usuari_factura.nif
    # Comprovem si existeix l'usuari a la base de dades
    endpoint = 'https://apabcn.secure.force.com/bookpurchase/services/apexrest/books?document=' + nou_nif
    resposta = HTTParty.get(endpoint)
    dades = resposta.to_hash
    @usuari_factura.nom = dades['nombre']
    @usuari_factura.nif = dades['nif']
    @usuari_factura.poblacio = dades['poblacion']
    @usuari_factura.provincia = dades['provincia']
    @usuari_factura.codi_postal = dades['codpostal']
    @usuari_factura.adreca = dades['direccion']
    #@usuari_factura.email = dades['email']
    @usuari_factura.email = current_user.email
    @usuari_factura.num_client = dades['numcliente']
    @usuari_factura.colegiat = dades['escolegiado']
    @usuari_factura.save(validate: false)
    if @usuari_factura.nif
      redirect_to usuari_factura_path(id: @usuari_factura.id)
    else
      @usuari_factura.nif = nou_nif
      @usuari_factura.save(validate: false)
      redirect_to edit_usuari_factura_path(id: @usuari_factura.id)
    end
  end

  # PATCH/PUT /usuari_factures/1
  # PATCH/PUT /usuari_factures/1.json
  def update
    respond_to do |format|
      if @usuari_factura.update(usuari_factura_params)
        format.html { redirect_to @usuari_factura, notice: 'Usuari factura was successfully updated.' }
        format.json { render :show, status: :ok, location: @usuari_factura }
      else
        format.html { render :edit }
        format.json { render json: @usuari_factura.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuari_factures/1
  # DELETE /usuari_factures/1.json
  def destroy
    @usuari_factura.destroy
    respond_to do |format|
      format.html { redirect_to usuari_factures_url, notice: 'Usuari factura was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuari_factura
      @usuari_factura = UsuariFactura.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usuari_factura_params
      params.require(:usuari_factura).permit(:user_id, :edifici_id, :nom, :adreca, :poblacio, :provincia, :pais, :codi_postal, :email, :num_client, :colegiat, :nif, :num_visat_ite)
    end
end

app/helpers/usuari_factures_helper.rb
module UsuariFacturesHelper
end

app/views/usuari_factures/_form.html.erb
<%= simple_form_for(@usuari_factura) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :user_id %>
    <%= f.input :edifici_id %>
    <%= f.input :nom %>
    <%= f.input :adreca %>
    <%= f.input :poblacio %>
    <%= f.input :provincia %>
    <%= f.input :pais %>
    <%= f.input :codi_postal %>
    <%= f.input :email %>
    <%= f.input :num_client %>
    <%= f.input :colegiat %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/usuari_factures/edit.html.erb
<h1>Editing Usuari Factura</h1>

<%= render 'form', usuari_factura: @usuari_factura %>

<%= link_to 'Show', @usuari_factura %> |
<%= link_to 'Back', usuari_factures_path %>

app/views/usuari_factures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Usuari Factures</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Edifici</th>
      <th>Nom</th>
      <th>Adreca</th>
      <th>Poblacio</th>
      <th>Provincia</th>
      <th>Pais</th>
      <th>Codi postal</th>
      <th>Email</th>
      <th>Num client</th>
      <th>Colegiat</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usuari_factures.each do |usuari_factura| %>
      <tr>
        <td><%= usuari_factura.user_id %></td>
        <td><%= usuari_factura.edifici_id %></td>
        <td><%= usuari_factura.nom %></td>
        <td><%= usuari_factura.adreca %></td>
        <td><%= usuari_factura.poblacio %></td>
        <td><%= usuari_factura.provincia %></td>
        <td><%= usuari_factura.pais %></td>
        <td><%= usuari_factura.codi_postal %></td>
        <td><%= usuari_factura.email %></td>
        <td><%= usuari_factura.num_client %></td>
        <td><%= usuari_factura.colegiat %></td>
        <td><%= link_to 'Show', usuari_factura %></td>
        <td><%= link_to 'Edit', edit_usuari_factura_path(usuari_factura) %></td>
        <td><%= link_to 'Destroy', usuari_factura, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Usuari Factura', new_usuari_factura_path %>

app/views/usuari_factures/new.html.erb
<h1>New Usuari Factura</h1>

<%= render 'form', usuari_factura: @usuari_factura %>

<%= link_to 'Back', usuari_factures_path %>

app/views/usuari_factures/show.html.erb
<div class="dark-background-container">
  <div class="row">
    <div class="medium-12 columns">
      <div class="projectes-external-container">
        <div class="heavy-title-container">
          <h2 class="heavy-title"><%= t('.titol') %></h2>
        </div>
        <div class="projectes-form-container">
          
          <div class="row">
            <div class="medium-12 columns">
              <div class="medium-6 columns">
                <div class="info-factura-item">
                  <%= t('.nom') %>:<br/> 
                  <span class="ressaltat"><%= @usuari_factura.nom %></span>
                </div>
                <div class="info-factura-item">
                  <%= t('.adreca') %>:<br/>  
                  <span class="ressaltat"><%= @usuari_factura.adreca %></span>
                </div>
                <div class="info-factura-item">
                  <%= t('.provincia') %>:<br/>  
                  <span class="ressaltat"><%= @usuari_factura.provincia %></span>
                </div>
                <div class="info-factura-item">
                  <%= t('.email') %>:<br/>  
                  <span class="ressaltat"><%= @usuari_factura.email %></span>
                </div>
              </div>
              <div class="medium-6 columns">
                  
                <div class="info-factura-item">
                  <%= t('.nif') %>:<br/>  
                  <span class="ressaltat"><%= @usuari_factura.nif %></span>
                </div>
                <div class="info-factura-item">
                  <%= t('.poblacio') %>:<br/>  
                  <span class="ressaltat"><%= @usuari_factura.poblacio %></span>
                </div>
                <div class="info-factura-item">
                  <%= t('.codi_postal') %>:<br/>  
                  <span class="ressaltat"><%= @usuari_factura.codi_postal %></span>
                </div>
              </div>
            </div>
          </div> 

          <div class="row">
            <div class="medium-12 columns">
            <%= link_to t('.procedir_pagament'), crear_pagament_path(edifici_id: @usuari_factura.edifici_id), class: "button small radius right botodreta" %>
            </div>
          </div>

          <div class="row">
            <div class="medium-6 medium-offset-3 columns">
              <div class="dades-info">
                <%= t('.explicacio') %><a href="http://isis.apabcn.cat/iris/Login.aspx">Oficina Virtual CAATEEB</a>
              </div>
            </div>
          </div>
                    

        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="medium-12 columns">
      <br>
      <%= link_to t('.tornar_projectes'), edificis_path %>
    </div>
  </div>
</div>