config/routes.rb
Rails.application.routes.draw do
  resources :empresa_factures
  resources :usuari_factures
  resources :empresa_facturas
  resources :usuari_facturas
  get 'documents/index'
  get 'edificis/pdf_header'

  resources :tresoreries
  resources :ingressos
  resources :despeses
  get 'planificacions/fases', to: 'planificacions#fases', :as => :fases_planificacio
  get 'planificacions/calendari', to: 'planificacions#calendari', :as => :calendari
  get 'planificacions/crea_valors_inicials', to: 'planificacions#crea_valors_inicials', :as => :crea_valors_inicials
  resources :planificacions
  resources :fases
  #get 'intervencions/assignacions', to: 'intervencions#assignacions', :as => :assignacions
  get 'intervencions/exporta_xml', to: 'intervencions#exporta_xml', :as => :exporta_xml
  resources :intervencions do
    collection do
      get :assignacions
      put :assigna
    end
  end

  resources :deficiencies
  resources :qualificacions

  get 'pagaments/crear_pagament', to: 'pagaments#crear_pagament', :as => :crear_pagament
  get 'pagaments/validar_dades', to: 'pagaments#validar_dades', :as => :validar_dades 

  resources :edificis do
    resource :download, only: [:show]
  end
  resources :identificacions
  
  devise_for :users
  get 'home/index'
  get 'home/contacta'
  get 'home/permisos'
  get 'home/tutorial'

  
  root :to => "home#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/deficiencia.rb
class Deficiencia < ApplicationRecord

	belongs_to :edifici

end

app/models/despesa.rb
class Despesa < ApplicationRecord

	belongs_to :edifici
	belongs_to :fase

end

app/models/document_pdf.rb
require "render_anywhere"
 
class DocumentPdf

  include RenderAnywhere
 
  def initialize(edifici)
    @edifici = edifici
  end
 
  def to_pdf
    url_header = 'http://progrehab.herokuapp.com/edificis/pdf_header?locale=ca'
    #kit = PDFKit.new(as_html, header_html: url_header, page_size: 'A4')
    kit = PDFKit.new(as_html, page_size: 'A4')
    kit.to_file("#{Rails.root}/public/programa.pdf")
  end
 
  def filename
    "Programa #{edifici.id}.pdf"
  end
 
  private
 
    attr_reader :edifici
 
    def as_html
      render template: "edificis/pdf", layout: "pdf", locals: { edifici: edifici }
    end


end

app/models/edifici.rb
class Edifici < ApplicationRecord

	has_one :identificacio
	has_one :qualificacio
	has_many :deficiencies
	has_many :intervencions
	has_many :fases
	has_one :planificacio
	has_many :ingressos
	has_many :despeses
	has_many :tresoreries
	has_many :pagaments
	belongs_to :user

end

app/models/empresa_factura.rb
class EmpresaFactura < ApplicationRecord

	belongs_to :edifici

	validates :nif, presence: true
	validates :email, presence: true
	validates :email, format: { with: URI::MailTo::EMAIL_REGEXP } 
	validates :nom_juridic, presence: true
  validates :adreca, presence: true
  validates :poblacio, presence: true
  validates :provincia, presence: true
  validates :codi_postal, presence: true

end

app/models/fase.rb
class Fase < ApplicationRecord

	belongs_to :edifici
	has_many :intervencions
	has_many :despeses

end

app/models/identificacio.rb
class Identificacio < ApplicationRecord

	belongs_to :edifici

	has_attached_file :foto_facana, :styles => { :original => "600x600>", :medium => "400x400>", :thumb => "200x200!" }, :default_url => "https://s3-eu-west-1.amazonaws.com/llibreedifici/missing/missing_facana.png"
  validates_attachment_content_type :foto_facana, :content_type => /\Aimage\/.*\Z/

end

app/models/ingres.rb
class Ingres < ApplicationRecord

	belongs_to :edifici

end

app/models/intervencio.rb
class Intervencio < ApplicationRecord

	belongs_to :edifici
	belongs_to :fase

end

app/models/pagament.rb
class Pagament < ActiveRecord::Base

	belongs_to :edifici
	belongs_to :user

end

app/models/planificacio.rb
class Planificacio < ApplicationRecord

	belongs_to :edifici

end

app/models/qualificacio.rb
class Qualificacio < ApplicationRecord

	belongs_to :edifici
	
	has_attached_file :xml_file
  
	#validates_attachment_content_type :xml_file, :content_type => ["application/xml"]
	#No estic validant perquè els arxius xml de les ITEs no tenen header i no passen la validació
	do_not_validate_attachment_file_type :xml_file

end

app/models/tresoreria.rb
class Tresoreria < ApplicationRecord

	belongs_to :edifici

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  #after_create :subscribe

  validates :first_name, :presence => true
  validates :last_name, :presence => true
  validates :nif, :presence => true

  def name
    [first_name, last_name].compact.join(' ')
  end

  def subscribe
		gibbon = Gibbon::Request.new(api_key: ENV['mailchimp_api_key'])
		list_id = ENV['mailchimp_list_id']
		gibbon.lists(list_id).members.create(body: {email_address: self.email, status: "subscribed", merge_fields: {FNAME: self.first_name, LNAME: self.last_name}})
	end

  has_many :edificis
  has_many :pagaments
  
end

app/models/usuari_factura.rb
class UsuariFactura < ApplicationRecord

	belongs_to :edifici

	validates :nif, presence: true
	validates :nif, format: { with: /\A[0-9]{8}[A-Z]\Z/,
    message: "NIF incorrecte" }
  validates :email, presence: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP } 
  validates :nom, presence: true
  validates :adreca, presence: true
  validates :poblacio, presence: true
  validates :provincia, presence: true
  validates :codi_postal, presence: true

end

app/controllers/fases_controller.rb
class FasesController < ApplicationController
  include CheckUser
  before_action :set_fase, only: [:edit, :update, :destroy]
  before_action :set_edifici, only: [:index, :assignacions]
  respond_to :html, :js

  def index
    check_user_edifici(params[:edifici_id])
    @subnavigation = true
    @submenu_actiu = 'fases'
    @fases = Fase.where(edifici_id: params[:edifici_id])
    @intervencions = Intervencio.where(edifici_id: params[:edifici_id])
  end

  def show
  end

  def new
    @fase = Fase.new
    @fase.edifici_id = params[:edifici_id]
    @intervencions = Intervencio.where(edifici_id: params[:edifici_id])
  end

  def edit
  end

  def create
    @fase = Fase.create(fase_params)
    @fases = Fase.where(edifici_id: @fase.edifici_id).order(:posicio)
    @intervencions = Intervencio.where(edifici_id: @fase.edifici_id)
    @edifici = Edifici.find(@fase.edifici_id)
  end

  def update
    @fase.update_attributes(fase_params)
    @fases = Fase.where(edifici_id: @fase.edifici_id).order(:posicio)
    @intervencions = Intervencio.where(edifici_id: @fase.edifici_id)
    @edifici = Edifici.find(@fase.edifici_id)
  end

  def destroy
    @fases = Fase.where(edifici_id: @fase.edifici_id).order(:posicio)
    @intervencions = Intervencio.where(edifici_id: @fase.edifici_id)
    @edifici = Edifici.find(@fase.edifici_id)
    @fase.destroy
  end

  def assignacions
    check_user_edifici(params[:edifici_id])
    @subnavigation = true
    @submenu_actiu = 'fases'
    @fases = Fase.where(edifici_id: params[:edifici_id])
    @intervencions = Intervencio.where(edifici_id: params[:edifici_id])
  end

  private
    def set_fase
      @fase = Fase.find(params[:id])
    end

    def set_edifici
      @edifici = Edifici.find(params[:edifici_id])
    end

    def fase_params
      params.require(:fase).permit(:edifici_id, :nom, :posicio, :observacions)
    end
end

app/helpers/despeses_helper.rb
module DespesesHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/edificis_helper.rb
module EdificisHelper
end

app/helpers/fases_helper.rb
module FasesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/fases/_form.html.erb
<%= simple_form_for(@fase, remote: true) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :edifici_id, :as => :hidden %>
    <%= f.input :nom %>
    <%= f.input :posicio %>
    <%= f.input :observacions %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, t('.guardar'), :class => 'button button-right' %>
  </div>
<% end %>

app/views/fases/_llistat_fases.html.erb
<% @fases.each do |fase| %>
	<h3 class="titol-fase">FASE <%= fase.posicio %>: <%= fase.nom %></h3>
	<p class="opcions-fase"><%= link_to t('.assignar_intervencions'), assignacions_intervencions_path(edifici_id: @edifici.id, fase_id: fase.id) %> | <%= link_to t('.editar_fase'), edit_fase_path(fase), remote: true %> | <%= link_to fase_path(fase, edifici_id: @edifici.id), remote: true, method: :delete,  data: { confirm: 'Segur que vols eliminar?' } do %>
				  
				  	<i class="fa fa-trash" aria-hidden="true"></i>
				  
				<% end %>
	</p>
	<div class="light-container">
		<div id="fases">
      <%= render :partial => '/fases/llistat_intervencions', locals: {fase_id: fase.id} %>
    </div>
	</div>
	<div class="spacer"></div>
<% end %>

app/views/fases/_llistat_intervencions.html.erb
<% if @intervencions.where(fase_id: fase_id).count > 0 %>
<table>
  <thead>
    <tr>
      <th><%= t('.descripcio') %></th>
      <th><%= t('.import_total') %></th>
    </tr>
  </thead>
  <tbody>
    <% @intervencions.where(fase_id: fase_id).each do |intervencio| %>
    <tr>
      <td><%= intervencio.descripcio %></td>
      <% import_total = intervencio.import_obres.to_i + intervencio.import_honoraris.to_i + intervencio.import_taxes.to_i + intervencio.import_altres.to_i %> 
      <td><%= import_total %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <p><%= t('.assigna_intervencions') %></p>
<% end %>

app/views/fases/create.js.erb
$('#fases').html("<%= escape_javascript(render 'llistat_fases') %>");
$('#modal-fase').foundation('close');

app/views/fases/destroy.js.erb
$('#fases').html("<%= escape_javascript(render 'llistat_fases') %>");

app/views/fases/edit.js.erb
$('#modal-fase').foundation('open');
$('#formulari-fase').html("<%= escape_javascript(render 'form') %>");

app/views/fases/index.html.erb
<div class="light-background-container">
  
  <div class="row">
    <div class="medium-12 columns">
      <div class="titol-seccio">
        <%= t('.titol_fases') %>
      </div>
    </div>
  </div>

  <div class="reveal" id="modal-fase" data-reveal>
    <h3 id="modalTitle"><%= t('.fase') %></h3>
    <div id="formulari-fase" class="formulari-fase">
    </div>
    <button class="close-button" data-close aria-label="Close modal" type="button">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="row">
    <div class="medium-12 columns">
      <div class="fases-container">
        <div id="fases">
          <% if @fases.exists? %>
            <%= render  :partial => '/fases/llistat_fases' %>
          <% else %>
            <p><%= t('.crear_fases') %></p>
          <% end %>
        </div>
        <div class="spacer"></div>
        <%= link_to (new_fase_path(edifici_id: params[:edifici_id])), remote: true do %>
          <span class="suma">+</span> <%= t('.afegir_fase') %>
        <% end %>
      </div>
    </div>
  </div>

</div>

app/views/fases/new.js.erb
$('#modal-fase').foundation('open');
$('#formulari-fase').html("<%= escape_javascript(render 'form') %>");

app/views/fases/update.js.erb
$('#fases').html("<%= escape_javascript(render 'llistat_fases') %>");
$('#modal-fase').foundation('close');