config/routes.rb
Rails.application.routes.draw do
  resources :empresa_factures
  resources :usuari_factures
  resources :empresa_facturas
  resources :usuari_facturas
  get 'documents/index'
  get 'edificis/pdf_header'

  resources :tresoreries
  resources :ingressos
  resources :despeses
  get 'planificacions/fases', to: 'planificacions#fases', :as => :fases_planificacio
  get 'planificacions/calendari', to: 'planificacions#calendari', :as => :calendari
  get 'planificacions/crea_valors_inicials', to: 'planificacions#crea_valors_inicials', :as => :crea_valors_inicials
  resources :planificacions
  resources :fases
  #get 'intervencions/assignacions', to: 'intervencions#assignacions', :as => :assignacions
  get 'intervencions/exporta_xml', to: 'intervencions#exporta_xml', :as => :exporta_xml
  resources :intervencions do
    collection do
      get :assignacions
      put :assigna
    end
  end

  resources :deficiencies
  resources :qualificacions

  get 'pagaments/crear_pagament', to: 'pagaments#crear_pagament', :as => :crear_pagament
  get 'pagaments/validar_dades', to: 'pagaments#validar_dades', :as => :validar_dades 

  resources :edificis do
    resource :download, only: [:show]
  end
  resources :identificacions
  
  devise_for :users
  get 'home/index'
  get 'home/contacta'
  get 'home/permisos'
  get 'home/tutorial'

  
  root :to => "home#index"
end

app/controllers/empresa_factures_controller.rb
class EmpresaFacturesController < ApplicationController
  before_action :set_empresa_factura, only: [:show, :edit, :update, :destroy]
  before_action :set_edifici

  # GET /empresa_factures
  # GET /empresa_factures.json
  def index
    @empresa_factures = EmpresaFactura.all
  end

  # GET /empresa_factures/1
  # GET /empresa_factures/1.json
  def show
  end

  # GET /empresa_factures/new
  def new
    @empresa_factura = EmpresaFactura.new
  end

  # GET /empresa_factures/1/edit
  def edit
    @edifici = Edifici.find(@empresa_factura.edifici_id)
  end

  # POST /empresa_factures
  # POST /empresa_factures.json
  def create
    @empresa_factura = EmpresaFactura.new(empresa_factura_params)
    #De moment anul·lo la validació al crear les dades de factura. Això és perquè primer es va a la pàgina de validació de dades, on l'usuari només ha de posar el NIF. Si tinc una validació d'altres camps com email no puc passar a la següent pàgina. Quan es faci l'update, en la confirmació de dades, sí que hi haurà validació de tots els camps, inclòs el NIF.
    if @empresa_factura.save(validate: false)

    else
      redirect_to validar_dades_path(@edifici.id), flash: { error: @empresa_factura.errors.messages }
      return
    end
    # Guardem el NIF introduït
    nou_nif = @empresa_factura.nif
    # Comprovem si existeix l'empresa a la base de dades
    endpoint = 'https://apabcn.secure.force.com/bookpurchase/services/apexrest/books?document=' + nou_nif
    resposta = HTTParty.get(endpoint)
    dades = resposta.to_hash
    @empresa_factura.nom_juridic = dades['NombreJuridico']
    @empresa_factura.nif = dades['cif']
    @empresa_factura.poblacio = dades['poblacion']
    @empresa_factura.provincia = dades['provincia']
    @empresa_factura.codi_postal = dades['codpostal']
    @empresa_factura.adreca = dades['direccion']
    @empresa_factura.pais = dades['pais']
    #@empresa_factura.email = dades[:get_empresa_response][:param_empresa][:email]
    @empresa_factura.email = current_user.email
    @empresa_factura.tipus_client = dades['tipocliente']
    @empresa_factura.save(validate: false)
    if @empresa_factura.nif
      redirect_to empresa_factura_path(id: @empresa_factura.id)
    else
      @empresa_factura.nif = nou_nif
      @empresa_factura.save(validate: false)
      redirect_to edit_empresa_factura_path(id: @empresa_factura.id)
    end
  end

  # PATCH/PUT /empresa_factures/1
  # PATCH/PUT /empresa_factures/1.json
  def update
    respond_to do |format|
      if @empresa_factura.update(empresa_factura_params)
        format.html { redirect_to @empresa_factura, notice: 'Empresa factura was successfully updated.' }
        format.json { render :show, status: :ok, location: @empresa_factura }
      else
        format.html { render :edit }
        format.json { render json: @empresa_factura.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /empresa_factures/1
  # DELETE /empresa_factures/1.json
  def destroy
    @empresa_factura.destroy
    respond_to do |format|
      format.html { redirect_to empresa_factures_url, notice: 'Empresa factura was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_empresa_factura
      @empresa_factura = EmpresaFactura.find(params[:id])
    end

    def set_edifici
      @edifici = Edifici.find(@empresa_factura.edifici_id)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def empresa_factura_params
      params.require(:empresa_factura).permit(:user_id, :edifici_id, :nom_juridic, :adreca, :poblacio, :provincia, :pais, :codi_postal, :email, :tipus_client, :nif, :num_visat_ite)
    end
end

app/helpers/empresa_factures_helper.rb
module EmpresaFacturesHelper
end

app/views/empresa_factures/_form.html.erb
<%= simple_form_for(@empresa_factura) do |f| %>
  <div class="row">
    <div class="medium-12 columns">
      
        <div class="form-inputs">
          <%= f.input :user_id, :as => :hidden, :input_html => { :value => current_user.id } %>
          <%= f.input :edifici_id, :as => :hidden, :input_html => { :value => @edifici.id } %>
          <div class="row">
            <div class="medium-6 columns">
              <%= f.input :nom_juridic %>
              <%= f.input :adreca %>
              <%= f.input :provincia %>
              <%= f.input :email %>
            </div>
            <div class="medium-6 columns">
              <%= f.input :nif %>
              <%= f.input :poblacio %>
              <%= f.input :codi_postal %>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="medium-12 columns">
            <div class="form-actions">
              <%= f.button :submit, t('.guardar'), :class => 'button small radius right botodreta' %>
            </div>
          </div>
        </div>
      </div>
    </div>
<% end %>

app/views/empresa_factures/edit.html.erb
<h1>Editing Empresa Factura</h1>

<%= render 'form', empresa_factura: @empresa_factura %>

<%= link_to 'Show', @empresa_factura %> |
<%= link_to 'Back', empresa_factures_path %>

app/views/empresa_factures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Empresa Factures</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Edifici</th>
      <th>Nom juridic</th>
      <th>Adreca</th>
      <th>Poblacio</th>
      <th>Provincia</th>
      <th>Pais</th>
      <th>Codi postal</th>
      <th>Email</th>
      <th>Tipus client</th>
      <th>Nif</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @empresa_factures.each do |empresa_factura| %>
      <tr>
        <td><%= empresa_factura.user_id %></td>
        <td><%= empresa_factura.edifici_id %></td>
        <td><%= empresa_factura.nom_juridic %></td>
        <td><%= empresa_factura.adreca %></td>
        <td><%= empresa_factura.poblacio %></td>
        <td><%= empresa_factura.provincia %></td>
        <td><%= empresa_factura.pais %></td>
        <td><%= empresa_factura.codi_postal %></td>
        <td><%= empresa_factura.email %></td>
        <td><%= empresa_factura.tipus_client %></td>
        <td><%= empresa_factura.nif %></td>
        <td><%= link_to 'Show', empresa_factura %></td>
        <td><%= link_to 'Edit', edit_empresa_factura_path(empresa_factura) %></td>
        <td><%= link_to 'Destroy', empresa_factura, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Empresa Factura', new_empresa_factura_path %>

app/views/empresa_factures/new.html.erb
<h1>New Empresa Factura</h1>

<%= render 'form', empresa_factura: @empresa_factura %>

<%= link_to 'Back', empresa_factures_path %>

app/views/empresa_factures/show.html.erb
<div class="dark-background-container">
  <div class="row">
    <div class="medium-12 columns">
      <div class="projectes-external-container">
        <div class="heavy-title-container">
          <h2 class="heavy-title"><%= t('.titol') %></h2>
        </div>
        <div class="projectes-form-container">
          
          <div class="row">
            <div class="medium-12 columns">
              <div class="medium-6 columns">
                <div class="info-factura-item">
                  <%= t('.nom') %>:<br/> 
                  <span class="ressaltat"><%= @empresa_factura.nom_juridic %></span>
                </div>
                <div class="info-factura-item">
                  <%= t('.adreca') %>:<br/>  
                  <span class="ressaltat"><%= @empresa_factura.adreca %></span>
                </div>
                <div class="info-factura-item">
                  <%= t('.provincia') %>:<br/>  
                  <span class="ressaltat"><%= @empresa_factura.provincia %></span>
                </div>
                <div class="info-factura-item">
                  <%= t('.email') %>:<br/>  
                  <span class="ressaltat"><%= @empresa_factura.email %></span>
                </div>
              </div>
              <div class="medium-6 columns">
                  
                <div class="info-factura-item">
                  <%= t('.nif') %>:<br/>  
                  <span class="ressaltat"><%= @empresa_factura.nif %></span>
                </div>
                <div class="info-factura-item">
                  <%= t('.poblacio') %>:<br/>  
                  <span class="ressaltat"><%= @empresa_factura.poblacio %></span>
                </div>
                <div class="info-factura-item">
                  <%= t('.codi_postal') %>:<br/>  
                  <span class="ressaltat"><%= @empresa_factura.codi_postal %></span>
                </div>
              </div>
            </div>
          </div> 

          <div class="row">
            <div class="medium-12 columns">
            <%= link_to t('.procedir_pagament'), crear_pagament_path(edifici_id: @empresa_factura.edifici_id), class: "button small radius right botodreta" %>
            </div>
          </div>

          <div class="row">
            <div class="medium-6 medium-offset-3 columns">
              <div class="dades-info">
                <%= t('.explicacio') %><a href="http://isis.apabcn.cat/iris/Login.aspx">Oficina Virtual CAATEEB</a>
              </div>
            </div>
          </div>
                    

        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="medium-12 columns">
      <br>
      <%= link_to t('.tornar_projectes'), edificis_path %>
    </div>
  </div>
</div>